### ISSUE TITLE
Files and folders

### ISSUE THREAD

**Issue by TomPed** [microservices/microservice-cli#21]
Allow support for files and folders. Need to attach the volumes when running a service.

**Comment by crabman96** [comment]
[text.txt](https://github.com/microservices/microservice-cli/files/2116928/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116933/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116934/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116940/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116942/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116943/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116944/text.txt)

[text.txt](https://github.com/microservices/microservice-cli/files/2116953/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116956/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116958/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116960/text.txt)
[text.txt](https://github.com/microservices/microservice-cli/files/2116961/text.txt)

**Comment by crabman96** [comment]
guys I'm really green here if I'm doing can you help     really     green
